# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout project from repo"
        uses: actions/checkout@v2
      - name: "Bulding project"
        uses: xlui/action-maven-cli@jdk15
        with:
          lifecycle: 'clean package'
          
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: cd /home/runner/work/java-demo-app/java-demo-app
      - name: "Running unit tests"
        uses: xlui/action-maven-cli@jdk15
        with:
          lifecycle: 'test site'
      - name: "Archiving unit test results as artifact"
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-results
          path: /home/runner/work/java-demo-app/java-demo-app/target/site
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: /home/runner/work/java-demo-app/java-demo-app/target/surefire-reports/*.xml
     
